# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsPilot < Formula
  desc "AI-powered CLI for Linux/macOS system administration"
  homepage "https://github.com/lpcoutinho/ops-pilot"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.4.0/ops-pilot_0.4.0_darwin_amd64.tar.gz"
      sha256 "92c4fc00b98a1de026e8f4922cb5b923f521682af5c9741570751ef3a301581a"

      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.4.0/ops-pilot_0.4.0_darwin_arm64.tar.gz"
      sha256 "071042f9208938e3ab8d10b9475fbbbc9f9a0a647a58ea6b831938f4395b0f4d"

      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.4.0/ops-pilot_0.4.0_linux_amd64.tar.gz"
      sha256 "2802b9260fe884e9c4a7a80171df449e939da456238f4fa2b4226ceae8650afc"
      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.4.0/ops-pilot_0.4.0_linux_arm64.tar.gz"
      sha256 "4e2ff7aa5a2b68b8a4119e091e0572828cb35e9d2c8eeb90a24dc34da6988049"
      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
  end

  test do
    system "#{bin}/ops-pilot --help"
  end
end
