# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpsPilot < Formula
  desc "AI-powered CLI for Linux/macOS system administration"
  homepage "https://github.com/lpcoutinho/ops-pilot"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.2.0/ops-pilot_0.2.0_darwin_amd64.tar.gz"
      sha256 "7d9cf24b7c15d08b4cbccec3970fbcc260ed75f9f27acc5e455b6e0d9304d9df"

      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.2.0/ops-pilot_0.2.0_darwin_arm64.tar.gz"
      sha256 "882fa38709fa06f075414fedb35523ef88cfa699d4a329ab9af3158d9d92ed6a"

      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.2.0/ops-pilot_0.2.0_linux_amd64.tar.gz"
      sha256 "c956f1f22cec24125077fc77f4258bb40d7f872dbb7572e1284bffc866598da0"
      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lpcoutinho/ops-pilot/releases/download/v0.2.0/ops-pilot_0.2.0_linux_arm64.tar.gz"
      sha256 "c9db57c666b352b0bd2fa7de801e090c7da88c8e1a66caf7e85d283f04c216d6"
      define_method(:install) do
        bin.install "ops-pilot"
      end
    end
  end

  test do
    system "#{bin}/ops-pilot --help"
  end
end
